/**
 * Deploys SparkFactory to the local node and writes the env files the app
 * needs, so a fresh clone goes from nothing to a working launchpad in one step.
 *
 * Run the node with forking on (the default) — that gives you the real Uniswap
 * V3 deployment from Robinhood Chain mainnet, so graduation actually creates a
 * pool locally instead of reverting.
 *
 *   npx hardhat node                                  # terminal 1
 *   npx hardhat run scripts/deploy-local.js --network localhost
 */
const fs = require("fs");
const path = require("path");
const { ethers } = require("hardhat");
const ADDRESSES = require("./addresses");

const ROOT = path.join(__dirname, "..", "..");
const MAINNET = ADDRESSES[4663];

async function main() {
  const [deployer, creator, alice] = await ethers.getSigners();
  const net = await ethers.provider.getNetwork();
  const chainId = Number(net.chainId);

  // The fork carries mainnet's Uniswap, so the same addresses work locally.
  const pm = await ethers.provider.getCode(MAINNET.positionManager);
  const forked = pm !== "0x";
  if (!forked) {
    console.warn(
      "\n  Uniswap V3 is not present on this node — start it with forking on\n" +
      "  (plain `npx hardhat node`). Trading will work; graduation will revert.\n"
    );
  }

  const Factory = await ethers.getContractFactory("SparkFactory");
  const factory = await Factory.deploy(
    MAINNET.positionManager, MAINNET.uniswapV3Factory, MAINNET.weth, deployer.address
  );
  await factory.waitForDeployment();
  const address = await factory.getAddress();
  const deployBlock = await ethers.provider.getBlockNumber();

  console.log(`SparkFactory  ${address}`);
  console.log(`chain         ${chainId}`);
  console.log(`uniswap V3    ${forked ? "present (forked mainnet)" : "MISSING"}`);

  write(path.join(ROOT, "frontend", ".env.local"), [
    "# Generated by contracts/scripts/deploy-local.js — safe to delete.",
    "REACT_APP_BACKEND_URL=http://localhost:8001",
    `REACT_APP_CHAIN_ID=${chainId}`,
    "REACT_APP_RPC_URL=http://127.0.0.1:8545",
    `REACT_APP_SPARK_FACTORY=${address}`,
    "",
  ]);

  write(path.join(ROOT, "backend", ".env"), [
    "# Generated by contracts/scripts/deploy-local.js — safe to delete.",
    "MONGO_URL=mongodb://localhost:27017",
    "DB_NAME=sparkfun_local",
    "SECRET_KEY=local-dev-only-not-a-secret",
    "CORS_ORIGINS=http://localhost:3000",
    `SPARK_CHAIN_ID=${chainId}`,
    "SPARK_RPC_URL=http://127.0.0.1:8545",
    `SPARK_FACTORY_ADDRESS=${address}`,
    `SPARK_DEPLOY_BLOCK=${deployBlock}`,
    "SPARKFUN_REQUIRE_SIGNATURE=true",
    "",
  ]);

  console.log("\nWrote frontend/.env.local and backend/.env");

  if (process.env.SEED !== "0") {
    await seed(factory, creator, alice);
  }

  console.log("\nImport a local account into your wallet to trade:");
  console.log(`  address     ${alice.address}`);
  console.log("  private key 0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a");
  console.log("  (hardhat's well-known test key — never use it anywhere real)");
  console.log("\nAdd the network manually if your wallet asks:");
  console.log(`  RPC http://127.0.0.1:8545   chain id ${chainId}   symbol ETH`);
}

async function seed(factory, creator, alice) {
  const tokens = [
    { name: "Midnight Pizza", symbol: "PIZZA", mayhem: false, dev: "0.3", buy: "1.1" },
    { name: "Cute Chaos", symbol: "MAYHEM", mayhem: true, dev: "0.1", buy: "2.5" },
    { name: "Little Blanket", symbol: "COZY", mayhem: false, dev: "0.2", buy: "0.6" },
  ];

  for (const t of tokens) {
    const tx = await factory.connect(creator).launch({
      name: t.name, symbol: t.symbol, metadataURI: "",
      quoteToken: ethers.ZeroAddress, mayhem: t.mayhem,
      devBuy: ethers.parseEther(t.dev), devBuyMinOut: 0,
    }, { value: ethers.parseEther(t.dev) });
    const rc = await tx.wait();
    const ev = rc.logs
      .map((l) => { try { return factory.interface.parseLog(l); } catch { return null; } })
      .find((l) => l && l.name === "TokenLaunched");

    const curve = await ethers.getContractAt("SparkCurve", ev.args.curve);
    await curve.connect(alice).buy(0, 0, ethers.ZeroAddress, { value: ethers.parseEther(t.buy) });
    console.log(`  seeded $${t.symbol}  ${ev.args.token}`);
  }
}

function write(file, lines) {
  fs.writeFileSync(file, lines.join("\n"));
}

main().catch((e) => { console.error(e); process.exit(1); });
